import { callAgent } from "./caller";

const PR_SYSTEM = `You are a developer writing a GitHub Pull Request description.
Given recent git commits and an AI code review summary, write a concise PR title and description.

Rules:
- title: max 70 characters, imperative mood ("Add", "Fix", "Refactor", "Update")
- body: 3-5 bullet points of what changed, then a brief AI review summary section
- Output ONLY valid JSON with exactly two keys: {"title": "...", "body": "..."}
- Use GitHub markdown in the body (## headings, - bullets)
- Do NOT wrap with markdown fences`;

export async function generatePRDescription(
  commits:      string[],
  avgScore:     number,
  keyFindings:  string[],
): Promise<{ title: string; body: string }> {
  const user =
`Recent commits:
${commits.join("\n")}

AI Review Score: ${avgScore}/10
Key findings: ${keyFindings.slice(0, 5).join(", ") || "none"}

Generate the PR title and description JSON.`;

  try {
    const raw    = await callAgent(PR_SYSTEM, user, "quality");
    const match  = raw.match(/\{[\s\S]*\}/);
    const parsed = JSON.parse(match?.[0] ?? "{}");
    if (parsed.title && parsed.body) { return { title: parsed.title, body: parsed.body }; }
  } catch { /* fall through to fallback */ }

  // Deterministic fallback
  const firstMsg = commits[0]?.replace(/^[a-f0-9]+ /, "") ?? "Update code";
  const bulletCommits = commits
    .slice(0, 5)
    .map(c => `- ${c.replace(/^[a-f0-9]+ /, "")}`)
    .join("\n");

  return {
    title: firstMsg.length > 70 ? firstMsg.slice(0, 67) + "..." : firstMsg,
    body:
`## Changes

${bulletCommits}

## AI Review Summary

Score: **${avgScore}/10**
${keyFindings.length ? `\nKey findings:\n${keyFindings.slice(0, 3).map(f => `- ${f}`).join("\n")}` : ""}

*Generated by 🦊 AI Code Reviewer*`,
  };
}
